### ISSUE TITLE
Ruby 2.1.5 issue with 'data-stripe' 

### ISSUE THREAD

**Issue by frgooall** [RailsApps/rails-stripe-coupons#1]
I'm getting this syntax error

syntax error, unexpected ':', expecting =>
...e}, { name: nil, 'data-stripe': 'exp-month' } );@output_buff...
...     

Using Ruby 2.1.5, not sure if anyone else has had similar issues.  Thanks!

**Comment by frgooall** [comment]
Changed error on _purchased.html.erb line 40 to the following and now the code works fine. 

From ->  <strong>'data-stripe': 'exp-month'</strong> to ->  <strong>'data-stripe' => 'exp-month'</strong>

Error occured when I used the composer

**Comment by paquettej** [comment]
I ran into this issue too. I solved it by changing the code to use the same syntax as the line handing the CVC:

 Change `'data-stripe': 'exp-month'` to `data: {stripe: 'exp-month' }`

I also had to change the following line as well to be  `data: {stripe: 'exp-year' }`

I am using ruby 2.1.5 and rails 4.2

**Comment by DanielKehoe** [comment]
I've updated the example application and the tutorial. Thanks for bringing this to my attention.
