### ISSUE TITLE
Additional Configurations

### ISSUE THREAD

**Issue by pwillikins** [RailsApps/rails-stripe-coupons#2]
I just spun up this example app and noticed that I needed to add additional configurations to my config/application.rb file in order for the environment variables to be accessed.  There were no instructions indicating how your environment variables would be accessed, it just tells you to put your credentials in a local_env.yml file.  Here is the code I added:

config.before_configuration do
      env_file = File.join(Rails.root, 'config', 'local_env.yml')
      YAML.load(File.open(env_file)).each do |key, value|
        ENV[key.to_s] = value
      end if File.exists?(env_file)
    end

This may not be an issue at all, but it kept me from moving forward.  Hope this helps. :)

**Comment by DanielKehoe** [comment]
Have you set up Unix environment variables in your shell? Should not need to set up anything else.
