### ISSUE TITLE
Error in full composer download

### ISSUE THREAD

**Issue by ghost** [RailsApps/rails-stripe-coupons#4]
I did the full composer download of the "rails-stripe-coupons" app. I wanted to see if it worked right out of the box without me having to config anything. I got an error on startup.

The error is in:
visitors/_purchase.html.erb
line 40
The entire line should be, and it worked after this change:
<%= select_month nil, { use_two_digit_numbers: true}, { name: nil, data: {stripe: 'exp-month' } } %> %>

**Comment by DanielKehoe** [comment]
Thanks for reporting that. I've updated the app in the repo.
